name: Strophodungeons

author: SchnTgaiSpock

description: A Slimefun addon that adds infinite dungeons to Minecraft

main: io.github.schntgaispock.strophodungeons.Strophodungeons

website: https://github.com/SchnTgaiSpock/Strophodungeons

version: ${project.version}

api-version: 1.14

depend:
- Slimefun

softdepend:
- SlimeHUD

commands:
  strophodungeons:
    description: /strophodungeons
    aliases: [sdungeons, sd]
    usage: Press [tab] for usage hints
  strophodungeonsschematic:
    description: /strophodungeonsschematic
    aliases: [sdschematic, sds]
    usage: Press [tab] for usage hints
    permissions: strophodungeons.schematic